// Header
export const GETHEADER_INPUT_VAL = 'GETHEADER_INPUT_VAL'
export const GETHEADER_INPUT_FOCUSED = 'GETHEADER_INPUT_FOCUSED'
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE'
export const HANDLE_INPUT_FOCUS = 'HANDLE_INPUT_FOCUS'
export const HANDLE_INPUT_BLUR = 'HANDLE_INPUT_BLUR'
export const HANDLE_INPUT_GETLIST = 'HANDLE_INPUT_GETLIST'
export const CHANGE_MOUSEIN = 'CHANGE_MOUSEIN'
export const HANDLE_CHANGE_LIST = 'HANDLE_CHANGE_LIST'
// Topic
// export const HANDLE_GET_LIST = 'HANDLE_GET_LIST'